### PR TITLE
[Thien] Implement get contact to Listview

### PR DESCRIPTION
**Pull request by kakakalot**
- Filter Name

### CODE REVIEW

**Review by octopitus — COMMENTED** [review]
Good job anh thien.

Just wonder why you need `redux` (with other related tools. `redux-logger`, `persist`, `thunk`, etc..) in this case? Why did you use `recompose` to access React's life-cycle method? 😳

**Comment by kakakalot** [comment]
- use `redux` to managing data-flow and state easier.
- use `recompose` to separate the UI and the logic action of a component.
two above thing is the structure of react/react-native to make the app more clearly and easy to read.

**Comment by octopitus** [comment]
Great. But we don't need `data-flow` stuff and `separate UI & logic` in this simple example. You will need a lot of time to setup, thus impact your final result.

I feel the 2nd challenge is not finish yet. Could you please finish it?

**Comment by octopitus** [comment]
Anyway, you are accepted. Congratz.

**Comment by kakakalot** [comment]
the 2nd was finished in last Thursday, `components/AnimationView`.
I placed it below ContactList, it may be overlapped.

**Pull request closed without merging**
